### ISSUE TITLE
Don't launch on High Sierra

### ISSUE THREAD

**Issue by jeremie-biron** [hexensemble/gb-usb-64m-cart-mac#1]
Hello!
I'd be super happy to use this project, but it looks that it doesn't launch on lasts macos versions.
Is the project still active? 

Thanks,
Jérémie

**Comment by hexensemble** [comment]
Hi!

I’m running macOS High Sierra 10.13.2 and it appears to be working fine for me.

Inside the application bundle there should be a folder called Contents/MacOS. Copy that whole folder to your Desktop or something and try running the file GBUSB64MCartMac.jar.

See if that works for you.

Jez
